{
 "title": "SmartZone Tests - Influxdb + Infinity",
 "description": "This dashboard uses Influxdb and a python script for time-series, and Infinity making API calls SmartZone to create the access point table",
 "tags": [
  "SmartZone",
  "Infinity",
  "Influxdb"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "serviceTicket", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Online APs - All domains in vSZ-h-sandbox",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"online\"\n  )"
    }
   ]
  },
  {
   "title": "Online APs - All domains in vSZ-h-sandbox",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"online\"\n  )"
    },
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"number\"\n  )"
    }
   ]
  },
  {
   "title": "Temperature and Humidity in Sunnyvale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nfrom(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"my_measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")\n\n  "
    }
   ]
  },
  {
   "title": "Total APs - All domains in vSZ-h-sandbox",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"number\"\n  )"
    }
   ]
  },
  {
   "title": "APs in vSZ-h-sandbox",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "columns": [
      { "selector": "name", "text": "Access Point Name", "type": "string" },
      { "selector": "serial", "text": "Serial Number", "type": "string" },
      { "selector": "mac", "text": "Mac Address", "type": "string" },
      { "selector": "zoneId", "text": "Zone ID", "type": "string" },
      { "selector": "apGroupId", "text": "AP Group ID", "type": "string" }
     ],
     "data": "{}",
     "json_options": {
      "columnar": false
     },
     "parser": "simple",
     "source": "url",
     "type": "json",
     "url": "https://your_SZ_FQDN:8443/wsg/api/public/v11_0/aps?serviceTicket=$serviceTicket",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": []
     }
    }
   ]
  }
 ]
}