{
 "title": "SmartZone Dashboard 2 - InfluxDB + CSV",
 "description": "This dashboard uses InfluxDB and a python script to create time-series visualizations, and CSV to create a pie chart and a table",
 "tags": [
  "SmartZone",
  "CSV",
  "InfluxDB",
  "Python"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AP Models",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "szApModels.csv",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Online APs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"online\"\n  )"
    },
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"number\"\n  )"
    }
   ]
  },
  {
   "title": "Total of Access Points",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"my_measurement\" and\n    r._field == \"number\"\n  )"
    }
   ]
  },
  {
   "title": "Access Point List",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "szAPs.csv",
     "schema": [
      { "name": "", "type": "string" }
     ]
    }
   ]
  },
  {
   "title": "Number of Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"Number of Clients\"] == \"All domains\")\n  |> filter(fn: (r) => r[\"_field\"] == \"clients\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Traffic in Bytes (Rx + Tx)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SmartZone\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"Total Traffic\"] == \"All domains\")\n  |> filter(fn: (r) => r[\"_field\"] == \"traffic\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}